# Generated by Django 5.1.4 on 2025-01-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfastofchampions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
