# Generated by Django 5.1.4 on 2025-01-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfastofchampions', '0002_markdowncontent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
