# Generated by Django 5.1.4 on 2025-01-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfastofchampions', '0004_alter_markdowncontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='intro',
            field=models.CharField(default='Nothing to see here!', max_length=500),
        ),
        migrations.AddField(
            model_name='markdowncontent',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='markdowncontent',
            name='image',
            field=models.ImageField(default='breakfastofchampions/static/hello.png', upload_to='assets/'),
        ),
    ]
