# Generated by Django 5.1.4 on 2025-11-02 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfastofchampions', '0005_markdowncontent_intro_markdowncontent_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='blog_header_image',
            field=models.ImageField(default='breakfastofchampions/static/blog_filler.png', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='markdowncontent',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2025, 11, 2, 17, 15, 19, 411115, tzinfo=datetime.timezone.utc)),
        ),
    ]
